services:
  # Backend Service (FastAPI)
  - type: web
    name: ai-financial-coach-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
    
  # Frontend Service (React)
  - type: web
    name: ai-financial-coach-frontend
    runtime: static
    buildCommand: cd professional-frontend && npm install && npm run build
    staticPublishPath: professional-frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: ai-financial-coach-backend
          property: host
